
server:
    port: 1001

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/maes
    username: root
    password: root

  jpa:
    properties:
          hibernate:
             ddl-auto: create
             dialect:  org.hibernate.dialect.MySQL8Dialect


